sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,kubernetes/deployment1.yaml,kubernetes/deployment2.yaml
sonar.projectKey=CI-CD-PIPELINE
sonar.organization=marouamaliki
sonar.host.url=https://sonarcloud.io
sonar.sources=.