name: workflow CI/CD 
on: 
  push:
    branches : [main]
  pull_request:
    branches : [main]
jobs:
  lint_test: 
    runs-on: self-hosted
    strategy:
      matrix:
        service: [microservices1, microservices2]
    steps: 
      - name: checkout the code 
        uses: actions/checkout@v4
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd ${{ matrix.service }}
          npm install
      - name: linting
        run: |
          cd ${{ matrix.service }}
          npm run lint
      - name: testing
        run: |
          cd ${{ matrix.service }}
          npm run test
  sonarquebe_scan:
    name: sonarqube_scan
    needs: lint_test
    runs-on: self-hosted
    steps:
      - name: checkout the code 
        uses: actions/checkout@v4
      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          # On utilise les variables d'env directement
          sonar-scanner \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.projectKey=CI-CD-PIPELINE \
            -Dsonar.sources=. \
            -Dsonar.exclusions=**/node_modules/**,**/dist/** \
            -X > sonar-report.log 2>&1

      - name: Run Trivy vulnerability scanner (SAST)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'          # 'fs' pour scanner le système de fichiers (ton code)
          format: 'sarif'          # C'est ici qu'on définit le TYPE d'artefact
          output: 'sonarqube-results.sarif' # Le nom du fichier qui sera créé
          severity: 'CRITICAL,HIGH' # On ne garde que le plus important
      - name: Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload Sonar Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sonarqube-report
          path: sonar-report.log




  # semgrep_scan:
  #   needs: lint_test
  #   runs-on: self-hosted
    
  #   # On utilise l'image Docker officielle pour éviter les problèmes d'install Python
  #   container:
  #     image: semgrep/semgrep
  #   env:
  #     SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
  #   steps:
  #     - name: checkout the code 
  #       uses: actions/checkout@v4
      
  #     - name: Run Semgrep CI
  #       run: semgrep ci
  #     - name: Upload Semgrep Report
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: semgrep-sast-report
  #         path: semgrep-report.sarif
  # codeql_scan:
  #   needs: lint_test
  #   runs-on: self-hosted
  #   permissions:
  #     security-events: write
  #     packages: read
  #     actions: read
  #     contents: read
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #       - language: actions
  #         build-mode: none
  #       - language: javascript-typescript
  #         build-mode: none
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4
  #   - name: Initialize CodeQL
  #     uses: github/codeql-action/init@v4
  #     with:
  #       languages: ${{ matrix.language }}
  #       build-mode: ${{ matrix.build-mode }}
    
  #   - name: Perform CodeQL Analysis
  #     uses: github/codeql-action/analyze@v4
  #     with:
  #       category: "/language:${{ matrix.language }}"
  